### PR TITLE
Merge remote-tracking branch 'ClusterM/stable'

### PR DESCRIPTION
**Pull request by NeoRame**
What was that? Now it Match with the other Icons ;)

### CODE REVIEW

**Comment by dbelyaev** [comment]
IMHO now it looks less detailed and dull.

**Comment by NeoRame** [comment]
Less detailed? where are the jamma port? chinch? the complete front in the other icon? label details?
it didn't match to all the other icons. the icons have a concept and a consistent style. ;)

**Comment by ClusterM** [comment]
I think that old version is more simple, and it's good.

**Comment by NeoRame** [comment]
More simple? I see more details and on the other hand, the "old"one doesn't match to all the icons. But it's ok, it's your choice.

I will post it with some color variations (asian, Europe, us Hispanic...) On GBATemp, for those people who want matching icons 😉

**Pull request closed without merging**
