### PR TITLE
Fixes for building hakchi2 with MonoDevelop

### PR DESCRIPTION
**Pull request by CeRiAl**
These changes make it possible to build **hakchi2** with **MonoDevelop on Linux**.

Basically it's just some changes of the case of several files, replaced the _PostBuildEvent_ for copying the language .dlls with a MSBuild-Task (works cross-platform) and a simple wrapper class to enable compilation of code which uses _ApplicationDeployment_ which isn't availabe in Mono (it tries to load `System.Deployment.dll` dynamically and uses a dummy implementation if it wasn't found).
Also I found a small bug in `Program.cs` which caused deletion of the language .dlls on runtime because of using platform-specific directory-seperators - this is also fixed.
Additionally the references to `/Properties/Resources.*.Designer.cs` were removed from the project file as they seem to be unnecessary - for example Visual Studio just generates empty zero-byte files.

The plan is (..._my_ plan is :wink: ) to have one binary of hakchi2 which runs on Windows as well as on Linux (or MacOS). For Linux, it just involves some minor changes - MacOS is on the plan later.

So, expect some other pull-requests regarding this in the future; but if you're not fine with this idea (just tell me, wouldn't be a problem), I would follow this plan/idea in a seperate fork.

**(Please note that the branch this pull request is based on has been rebased several times, so be sure to use a fresh clone or reset your local branch to origin before you re-try building!)**

**UPDATE:**
After a simple change of udev-permissions on my system, I just successfully dumped a kernel from my SNES-mini (note that this took no further changes to the code - just the modifications in this pull-request). :tada: 
Didn't try more yet, but for other functions I'm sure the code needs some more (simple) changes (don't use the packaged win32-tools but the system ones, etc.)

----

### Tested building/running on:

**Visual Studio Community 2015 on Windows 7 Ultimate x86 SP1**
- **WORKS** (did not find any problems here)

**elementary OS 0.4.1 Loki x64 (Ubuntu 16.04)
with latest Mono release (5.4.1) from mono-project.com via official Mono repository**
- **MonoDevelop 5.1.0** (from default Ubuntu repository)
  - build **FAILS** because of incorrectly recognized relative path references (like MD 6.1.2),
    and unresolved references to namespace .Properties (may be fixable, but as MD 5.1.0 is very old I didn't try further) 

- **MonoDevelop 6.1.2** (FlatPak)
  - **works** only with pregenerated `/Properties/Resources.Designer.cs` from VS or other working MD versions,
    **OR** by manually changing relative path references in `/Properties/Resources.resx` from
      `..\folder_images\` to `../folder_images/`
      `..\images\flags\` to `../images/flags/`
      `..\images\` to `../images/`
    and manually regenerating `/Properties/Resources.Designer.cs`
    (did _not_ add these changes to the pull request because it seems to be a bug with older MD/resgen.exe versions only)
      
- **MonoDevelop 6.3.0.864**
  - **WORKS** (current "reference platform" for building hakchi2 on Linux)

- **MonoDevelop 7.3.0.708** (Preview)
  - build **FAILS** with some obscure resgen.exe reference error - needs further investigation

### CODE REVIEW

**Comment by danmcgoo** [comment]
Hello,

Firstly, I would like to thank you to have taken the initiative to fix the build of hakchi2 for MonoDevelop.
It would be very helpful for all linux users out there.

However, I have the following build errors when trying to build your branch (CeRiAl:monodevelop-build-fixes) under Ubuntu 16.04.3 LTS (see attached file).
[build-errors.log](https://github.com/ClusterM/hakchi2/files/1465291/build-errors.log)

**Comment by CeRiAl** [comment]
@danmcgoo:
Yes, that seems to be a limitation of the MonoDevelop build-environment - I also got this when I tried to run it the first time.
The fix is easy:
Open the corresponding .resx file in MonoDevelop, make a simple change (I added a space in the beginning of the file) - **undo** it again - and save.
MonoDevelop should now generate the .Designer.cs file.
I will add a README for Linux users as soon as everything is running smooth.

**Comment by danmcgoo** [comment]
@CeRiAl, thank you for the tip.
However, I have 2 errors left related to the Resources.resx file (see attached file).
[Resources-build.log](https://github.com/ClusterM/hakchi2/files/1465708/Resources-build.log)

**Comment by CeRiAl** [comment]
@danmcgoo, I think you just forgot to touch the file "Resources.resx" (just like the other language-specific resources).
The warning "Reference 'System.Deployment' not resolved" is not really a problem on Mono, because the reference isn't actually used in the code (and System.Deployment isn't supported on Mono).

**Comment by danmcgoo** [comment]
@CeRiAl, actually I also touched the "Resources.resx" file, that's why I am now clueless on how to solve this issue...

**Comment by CeRiAl** [comment]
@danmcgoo:
I could reproduce this behaviour with the current stable version of MonoDevelop (6.1.2), too.
I'm using a self-compiled version of MonoDevelop (6.3.0.864), because I don't like the default "flatpak" isolation, it works fine on this version.
It seems the older version has a bug with the relative pathnames to the .pngs in the images folder (backslashes/windows-style instead of forward-slashes).
You can fix this locally (replace "..\XXX\XXX.png" with "../XXX/XXX.png" to get your build running, but I really wouldn't recommend to put this into the actual code, bc. it was fixed in newer MonoDevelop versions and it might break the Windows build...

**Comment by danmcgoo** [comment]
@CeRiAl 
Thank you again for the solution.
However, after doing so I have more errors.
By the way, I am using the version of MonoDevelop present in the repository of in Ubuntu 16.04.

**Comment by CeRiAl** [comment]
@danmcgoo:
I'm sorry that none of these solutions work for you... :/ The version of MonoDevelop provided by the Ubuntu 16.04 repositories is very old IMHO, 5.10 last time I checked, can you confirm this?
So you should really install a newer version (which is actually advised on the MonoDevelop homepage) - either the "flatpak" version I mentioned above (6.1.2), or a self compiled-version (6.3.0.864 - which is the latest in the 6.x branch, or even a 7.x MonoDevelop).
There have been a lot of changes in Mono(Develop) in the last 2-3 years, so 5.10 is sadly quite outdated...
(FYI: I'm also using a Ubuntu 16.04-based distro here - elementaryOS - so it's not that I'm using something completely different to get it running)

Update:
If you want to try with my self-compiled version of MD 6.3.0.864 (compiled on Ubuntu 16.04-x64):
https://cloud.cryptopath.org/owncloud/index.php/s/PyODqFMQGmzYUN3
Just drop it into `/opt` and run with `/opt/monodevelop-6.3.0.864/bin/monodevelop`

**Comment by CeRiAl** [comment]
@danmcgoo, please feel free to have a try again, I have made quite some changes to the branch, please also note the previous comment (reg. MonoDevelop 6.3) and the very first comment :wink:

**Comment by danmcgoo** [comment]
@CeRiAl, thank you for your effort.
I have checked it quickly today, it's a lot better. However, I have still some issues.
But I still not have tried with MonoDevelop 6.3 yet. I should try to install it first, and then I might give you more useful comments.

**Comment by ClusterM** [comment]
Thank you!

**Pull request merged**
