### PR TITLE
Create snes.xml game database

### PR DESCRIPTION
**Pull request by barryvdh**
Similar to nescarts.xml, this create a SNES database.

Resources used: 
https://github.com/eesperan/hyperspin-config/blob/master/Databases/Super%20Nintendo%20Entertainment%20System/All%20Game.xml for checksum mapping to names and region.
http://wiki.thegamesdb.net/index.php/API_Introduction for additional information (release date, cover art, number of players, publisher etc)

I've correct some names to get better mapping, it misses only a few checksums from the API, but 776 games are included.

I've tested this with a few roms and it does seem to match.

Ofcourse this isn't useful without additional code, but it's a start.

### CODE REVIEW

**Comment by HardKnorr** [comment]
There is another cool snes.xml Database which is slightly larger and also got informations about the playercount, maybe a completely scraped tgdb ?
have a look at 
Resources used: 
https://github.com/recalbox/recalbox-gamelists/blob/master/gamelists/snes/gamelist.xml

Cheers !

**Comment by barryvdh** [comment]
tgdb does include more games (1800 or so), but it doesn't include the checksums. So I've only scraped the games which match a game from the XML with checksums included. The resource you linked looks like the same information.

**Comment by HardKnorr** [comment]
ah now i understand but your list didn't include a playercount, so it would be nice to use the best of both worlds :-)

**Comment by barryvdh** [comment]
It does include playercount (when available) and co-op mode

```xml
  <Game>
    <name>Super Mario Kart</name>
    <players>2</players>
    <simultaneous>0</simultaneous>
    <crc>cd80db86</crc>
    <date>1992-09-01</date>
    <publisher>Nintendo</publisher>
    <region>USA</region>
    <cover>http://thegamesdb.net/banners/boxart/original/front/41-1.jpg</cover>
    <api_id>41</api_id>
  </Game>
```

(Only the simultaneous/co-op doesn't seem to be filled that often)

**Comment by HardKnorr** [comment]
well looks like my fault then i've referred to your link instead on your attached .xml ;-)
(sorry new to github ...)

**Comment by barryvdh** [comment]
Yeah I've used 2 sources, 1 with checksums but no extra data, and one with players, cover etc but no checksums. I combined those together based on name so now we have both :)

**Comment by ClusterM** [comment]
Thank you!

**Comment by barryvdh** [comment]
Thanks for merging and adding the code! Could also be useful perhaps to use the cover art from here, might be more reliable then Google images, but not sure how easy that is to implement.

**Comment by ClusterM** [comment]
Yes, I added cover downloading code.

**Comment by marcmam2** [comment]
@ClusterM should Hakchi2 automatically download the cover from the address at the `<cover>` field on snescarts.xml ? Because if so, that is not what I am getting
Untitled
Thanks!

**Pull request merged**
