### PR TITLE
Game tree view

### PR DESCRIPTION
**Pull request by elierodrigue**
image

Working by system treeview as well as normal sorted checked list box.

### CODE REVIEW

**Comment by MiLToS666** [comment]
This is looking good, care to provide a compiled .exe to test it out? :)

**Comment by elierodrigue** [comment]
Replace latest .exe with that one

[hakchi.zip](https://github.com/ClusterM/hakchi2/files/991186/hakchi.zip)

**Comment by MiLToS666** [comment]
I'm getting this error on launch. Then hakchi runs but it doesn't read my game library, shows only the 30 default games. :(

**Comment by elierodrigue** [comment]
i would need to know which system game you have as well as file extension.

**Comment by MiLToS666** [comment]
I have the following systems and ALL my games are .7z compressed with correct command line for every system.

**Comment by elierodrigue** [comment]
Any way you can zip me your hakchi folder? Its because there's a lot of system hakchi doesnt know about. I'll set most of them and make sure it doesnt crash when there's an issue.

**Comment by MiLToS666** [comment]
Yes I will send it to you. I will upload it overnight and provide the link in your email if you'd like.

**Comment by elierodrigue** [comment]
[hakchi.zip](https://github.com/ClusterM/hakchi2/files/992762/hakchi.zip)

Here's an exe that should fix it. It will list some game in  an "Unknow" folder but at list it wont crash.

**Comment by MiLToS666** [comment]
Thank you, I will try this new .exe when I go home tonight. If you still want my hakchi folder that I uploaded for you, let me have your email and I will send you the link!

**Comment by elierodrigue** [comment]
er@nubik.ca

**Comment by elierodrigue** [comment]
elierodrigue@gmail.com

**Comment by MiLToS666** [comment]
It doesn't crash now and the tree view is great! It takes a very long time (to the point you think the program stopped responding) when you try to de-select a whole category though, is that normal? You can add Atari Lynx, Atari 7800, SuperGrafx category too and leave the "Unknown" for some others. Check the link I sent you with my setup. 👍

**Comment by elierodrigue** [comment]
[hakchi.zip](https://github.com/ClusterM/hakchi2/files/998144/hakchi.zip)

@MiLToS666 Try this build, should fix all of your issues.

**Comment by MiLToS666** [comment]
No problems at all and all my systems listed! Well done! 👍

**Comment by KMFDManic** [comment]
@elierodrigue, how are you! Last Helping Tree release was great!  I did some testing for you with the "system tree" and also posted a video.  There are a few conflicts I will address, and my recommendations for possibly how to fix them:)

-Object Reference Point not set to an instance of an object = Systems that cannot be classified, get rejected with this error.  Unless you have specially marked extensions, you should have this error get ignored, and the rejected files either devalued (not shown at all in "System Tree", but left alone in A-Z), or thrown into Unknown Classification Status on "System Tree" Tab.  Obviously, Sega CD, 3D0, Turbografx-CD, Playstation 1, and "Rom" files, etc, will be very difficult to ever classify.  So, other than the "main" known system extensions, I would revert all ignored, errored out files to "unknown" folder, or just ignore them from the "System Tree" entirely:)  

-Selection of games in "System Tree" takes approximately 3 seconds each.  This, I know, will take a little bit to clean up the memory usage, so it can access the files faster!  But, it is still workable:)

-If you can integrate, like in "Custom Folder Management", ability to use SHIFT+CTRL Multiple or Selective File shortcuts, this would be a godsend!  Instead of clicking one file at a time, holding SHIFT at first file, then SHIFT at the last FILE, will select all files in between:)  And, CTRL allows selective.  I am sure you already know this!  I was just clarifying my meaning:)

Here is the VIDEO link.  Note, the "Object Reference Point not set to an instance of an object" error replicates each time you open Hakchi2.  You just have to close the error with ENTER key on keyboard, til it clears all instances of files that are unknown and unsupported via your "System Tree".  AND, files that are seemingly deleted from using your modified hakchi2 version, are reverted back to normal status upon replacing hakchi2 exe with the original:)  So, no true file deletion occurs!  So, that is a good thing:)

https://www.youtube.com/watch?v=vvyvjzkFI64

Great work!  Looking forward to seeing how you address these mentioned issues:)

**Comment by elierodrigue** [comment]
@KMFDManic  Is that using the latest build? 
Pretty sure the not set to an instance of an object is most likely fixed as well as the checkbox delay...

My next update will be to be able to customize system detection through a config file, i will quickly need @ClusterM  to merge the pull request and or to add me to the list of contributer as its the list of changes i made are getting pretty big.

**Comment by KMFDManic** [comment]
I will check on the "latest" build that is "mastered".  As far as config file.  Only systems with known extension types, such as .vb, .z80, can be truly detected.  You won't be able to distinguish between Sega CD or Playstation 1, and so on.  But, you can certainly tell which are Virtual Boy games:)

**Comment by KMFDManic** [comment]
Ok, my test results, still stick.  I "was" using your current build.  Once the errors are skipped, if I attempt to add a Nintendo Virtual Boy Game, or a ZX Spectrum game, and other ones it doesn't accept and cannot read, it gives the same "not set to an instance of an object" error.  This was tested with most current builds of debug and standard hakchi2 2.17.  I have systems integrated (and, odd file extensions), that many others do not, hence, the errors:)  If you post any other builds here, I will test, accordingly:)

**Comment by elierodrigue** [comment]
[hakchi.zip](https://github.com/ClusterM/hakchi2/files/999502/hakchi.zip)

@KMFDManic  try this out. Performance should be much better now and it support almost all of your systems without any issues.

**Comment by KMFDManic** [comment]
Ok, it works nicely.  Improvements I noticed.

-Selection -Deselection is faster, instead of 3 seconds, it is now roughly 1.5 seconds.  What did you do to reduce time?

As of right now, the "System Tree" just needs time reduced for selection, deselection process:)  Otherwise, it is awesome!

-I will edit the SystemsDetection file, to cover "my systems".  I will additionally email you when I am ready for you to "test" my "V2".  Some things I plan on doing for V2, I will let you know via email.  These involve specialized compression for a few particular systems.

**Comment by elierodrigue** [comment]
@KMFDManic  it was mostly the way i handled  check uncheck. Too many full system size recalculation were fired.

**Comment by MiLToS666** [comment]
Loving it! I like how we can easily add more systems now and I have named the systems just the way I like them! 👍

**Comment by KMFDManic** [comment]
I made modifications to the system detection, to branch out from /bin/32x to 32X and Sega CD, as separate entities in the "tree".  I did the same for ColecoVision and other anomalies
system test
.  Any systems that get mixed, I will fix on my end.  I will send you my adjusted file, so you can test it out, when I am done:)

**Comment by KMFDManic** [comment]
Note: Possible Bug:  Try adding Games with the current "tree build".  It hangs, then gives unhandled exception error.  Then, the "instance of an object, error.

**Comment by elierodrigue** [comment]
Which kind of game?

Elie Rodrigue
Nubik.ca
1-888-NUBIK-55 ext 700

**Comment by KMFDManic** [comment]
I tested it on my V2 set.  Your previous hakchi allowed me to add games.  This one does not.  It would not let me add any game without hanging.  It could just be on my end.  I would have to test a couple more perimeters.

**Comment by KMFDManic** [comment]
I tried an snes game, since its common.

**Comment by KMFDManic** [comment]
This only occurs with current hakchi on V1 and V2 for me, with this newest build  As mentioned, it can be entirely on my end.  Previous build adds games just fine:)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at com.clusterrr.hakchi_gui.MainForm.AddGames(IEnumerable`1 files)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
hakchi
    Assembly Version: 2.0.17.19
    Win32 Version: 2.0.17.19
    CodeBase: file:///C:/_VUZE/KMFDManic%20Mini%20NES%20V2/KMFDManic%20(2.17)%20(V2)/hakchi.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5492 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Deployment
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5493 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Deployment/2.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.2.20802
    CodeBase: file:///C:/_VUZE/KMFDManic%20Mini%20NES%20V2/KMFDManic%20(2.17)%20(V2)/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.4506.5463 (Win7SP1GDR.030729-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_64/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by elierodrigue** [comment]
i tried adding snes games from smc file or 7z files and both work perfectly...

**Comment by KMFDManic** [comment]
I will fix it on my end.  I thought it would be a conflict with my setup.  The log shows where I will have to look.

**Comment by KMFDManic** [comment]
Anyways, you are doing great.  And, the end result of the system tree will be great!  You should take the time to play a few games!

**Comment by KMFDManic** [comment]
I will email you a "test" hakchi2 "games" folder with some systems that might not properly be recognized, yet.  I will do a few adjustments to the "detections" file, and let you finalize it:)  Some systems will not run in compressed form.  Others will.  I will account for each case, scenario, for the systems that are not yet in Detections.

**Comment by elierodrigue** [comment]
Great
There's a flag in the config file that will make hakchi compress the games or not.
It should be working for all system except nes for now.

**Comment by KMFDManic** [comment]
I succeeded in editing the config file, so that it detects Amistad CPC, Sega CD, ZX Spectrum, and so on.  The only conflict is getting FDS games to detect properly.  

You have...

  },
  {
    "Prefix": "D",
    "Image": "blank_fds.png",
    "SupportZip": true,
    "SystemName": "Famicom Disk System",
    "Executable": "/bin/nes",
    "Extensions": [
      ".fds"
    ]

See if you can "get" Famicom Disk System to show up in the system tree tab, by adding a FDS game.    Paste that code here, if you get it going:)  I will play around more, tomorrow:)

**Comment by elierodrigue** [comment]
They do work for me... importing .fds from drag and drop, non compressed.
image

**Comment by KMFDManic** [comment]
I emailed you my file, as well as one I set up to stay 7zipped, upon adding.  Good thing is, Amistad cpc, ZX Spectrum both support 7zip:)  I also included the .ini file, so you can see the adjustments I made.  I left FDS alone for now.  Thanks!

**Comment by KMFDManic** [comment]
I added in non compressed form, and it still did not trigger the system tree.  At least every thing else I add works great, for now:)

**Pull request merged**
