### PR TITLE
Add Sort Title (SortRawTitle) to Game options

### LINKED ISSUE #345: Add "Sort Title" field for control over game sequence
It would be nice if there was a "Sort Title" field for each game that would be the one that would determine the sort order within a folder.  The stock NES Classic must use something like this to get "The Legend of Zelda" and "Zelda II - The Adventure of Link" to appear next to each other.

### PR DESCRIPTION
**Pull request by juanlin**
Added a textbox to read/edit SortRawTitle, to help order games by alphabet. Fixes #345 
Not sure about MainForm.resx. I changed the UI by hand, and VS2017 spit out the result.

### CODE REVIEW

**Comment by gnadenlos** [comment]
Thank you, this would be very useful - I don't understand how NES Mini users could work for over one year without this feature.

**Comment by ClusterM** [comment]
Why you need it if games are sorted alphabetically anyway?

**Comment by gnadenlos** [comment]
If you have a title like "The Legend of Zelda" and want it sorted as "Legend of Zelda" you need the SortRawTitle, so the display title would still be "The Legend of Zelda" but it would be sorted as letter "L".

You could also use it for the many games starting with the word "Super". If you don't do that 1/4 of your games will be in the "T" and "S" folder.

It's also possible to use the SortRawTitle to group games by system, if you add the system in the SortRawTitle - thinking about it, it would be better to use the field Publisher for that. So you could have both options (by title or by system) and only lose the less interesting "sort by publisher".

**Comment by juanlin** [comment]
Exposing the Sort Title to the user is handy when sequels have no numbers (eg: Super Star Wars games—Super Star Wars, SSW: The Empire Strikes Back, SSW: Return of the Jedi—would have Sort Titles Star Wars 1, Star Wars 2, Star Wars 3)

Or when sequels have a different naming convention (provided by #345):
The Legend of Zelda, followed by Zelda II: The Adventure of Link (Sort Titles: "zelda 1", "zelda 2". Or "legend of zelda", "legend of zelda 2").

Another example, sorting "Disney's Aladdin" under A for Aladdin.

The option to edit Sort Title offers the user more flexibility to order games in how they perceive is the proper order, even when names are slightly out of alphabetical order.

**Pull request closed without merging**
