### PR TITLE
Added Japanese(ja-JP) Translations

### PR DESCRIPTION
**Pull request by kleusbalut**
many thanks for useful tools.

SNES mini now on sale in Japan.
I Translated Japanese Strings.

please check files and merges!

### CODE REVIEW

**Comment by gslance** [comment]
The translations are automatically generated with an external file, not through these Resource files. You can request helping translate to Japanese, it is done with an external excel sheet (Google Sheets).

**Comment by kleusbalut** [comment]
thanks for replying.
I understood translation procedure.

can i get translation access the Google Spreadsheet file?

**Comment by gslance** [comment]
Please [follow this link](https://docs.google.com/spreadsheets/d/1yrXH-6g61klKmuXTVf3f0ah8DCQObu-9YEJRoWTeuik) and request access there. @ClusterM  will review your application. Thank you for your hard work!

**Comment by kleusbalut** [comment]
thank you!
sent request.

best regards.

**Comment by Mad-Mega** [comment]
@gslance 
Was there something wrong about my translations?

**Comment by gslance** [comment]
@Mad-Mega 
In broad lines, no. But scatterered were typo's (e.g 'alstjeblieft' for 'alsjeblieft'), inconsistencies with what's on-screen (e.g 'a.u.b' elsewhere 'alsjeblieft'), too long sentences or mismatched synonyms for UI usage (e.g 'onderbrekings Beheer' vs. 'Opslagpunten Beheerder' for Save State Manager). I went by each and every line, and occassionally asking colleagues at a school I teach at for revisions.  

I've been doing this for the last week or so, making sure it's always up to date and properly translated. Especially in light of an imminent release.

**Comment by Mad-Mega** [comment]
Cool...i have no problem with it, as long as it serves the program :-) 👍

**Comment by gslance** [comment]
@Mad-Mega 
I apologize if it came off as aggressive editing! I meant no disrespect. I hope we can collaborate together for a superb dutch translation and serve our nation to allow better understanding of hakchi2!

**Pull request closed without merging**
