### PR TITLE
Lots of English grammar/spelling fixes

### PR DESCRIPTION
**Pull request by asiansteev**
I tried to keep the phrasing the same as @ClusterM intended, but fix grammar and spelling. I tried to move to a more consistent language as well and match language used by Nintendo. some of the changes include
```diff
- led
+ LED
- savestates
+ Suspend Points
- fel1
+ FEL-1
- "Recycle Bin" folder
+ the Recycle Bin
- .png and .jpg format
+ PNG and JPEG format
- command line
+ command-line
- read only
+ read-only
- user friendly
+ user-friendly
- Hakchi2
+ hakchi2
- Nes Mini
+ the Nes Mini
+ your Nes Mini
```
we also use a lot of "covers", "cover art" and "box art" interchangeably. I changed most of them to "box art" but could change them back to cover if needed.
there's also this change that I believe was a typo, the data name was Fel1, but the value said Fes1. I changed it to FEL-1...
```diff
<data name="ExecutingFel1" xml:space="preserve">
-  <value>Executing fes1...</value>
+  <value>Executing FEL-1...</value>
</data>
```
i also added some links to the README
also the description of the project should be changed.
```diff
- Tool that allowes to add more games to NES Classic Mini
+ Tool that allows you to add more games to the NES Mini 
```

### CODE REVIEW

**Comment by baconcow** [comment]
Tool that allows you to add more games to **the** NES Classic Edition / NES Classic Mini: Famicom.**

**Comment by asiansteev** [comment]
@baconcow for consistency, I added the full title to the beginning of the README, but for every other case, I'm using "NES Mini" I think the description is an appropriate place for "NES Mini"

**Comment by baconcow** [comment]
@asiansteev Makes sense. Your corrections look good. I would still consider adding "the".

**Comment by asiansteev** [comment]
@baconcow absolutely, i'll change the description

**Comment by madmonkey1907** [comment]
fes1.bin is correct

**Comment by asiansteev** [comment]
@ClusterM what name are you referring to?

**Comment by Hedda** [comment]
NES should also always be written in capital (upper-case) letters since it is an abbreviation for "Nintendo Entertainment System". 

* If you write is as "Nes" with only the first letter beginning with a capital letter it reads as if it is a name and not an abbreviation.

**Comment by ClusterM** [comment]
Thank you!

**Pull request merged**
