### PR TITLE
 Add new Icons and Blank Cover!

### PR DESCRIPTION
**Pull request by NeoRame**
For the new RetroArch support i add new Blank Cover for the Main Gui and for the Folder Manager new small Icons and sm_tr

New Systems Images/ Icons:
-GameBoy
-GameBoy Color
-GameBoy Advance
-Famicom Disk System
-Famicom
-SNES US 
-SNES EUR/JAP
-PCEngine
-Genesis/MegaDrive
-Sega Master System
-RetroArch 8Bit Style Blank Image

!!! All images uncompressed, when i'm home i compress this stuff and reupload it.!!!!!

### CODE REVIEW

**Comment by ClusterM** [comment]
It's looks awesome! =) But I have not wrote code for it (yet?)

**Comment by NeoRame** [comment]
I know, but I thought maybe for the future 😉For cosmetic updates

**Comment by ClusterM** [comment]
Nintendo 64 missed :(

**Comment by NeoRame** [comment]
I Work on it. 😉

**Comment by NeoRame** [comment]
Done, look at the pull request 😊

**Pull request merged**
