### PR TITLE
Screenshot without tearing

### PR DESCRIPTION
**Pull request by gyuque**
Screenshot images often include tearing because frame buffer is updated while capturing.
This patch adds routines to pause/resume canoe emulator before/after capturing.

### CODE REVIEW

**Comment by ClusterM** [comment]
But this works only with canoe. Hmm...

**Comment by gyuque** [comment]
I'm not using unofficial emulator...
But supporting home screen is good for me.

**Comment by gyuque** [comment]
Following pattern works good for me (SNES official emulator and home screen)

**1st:**  ps|grep [c]anoe
**2nd(if 1st didn't match):** ps|grep [R]eedPlayer-Clover

I can add a pattern for kachikachi easily but I have no NES mini to verify it.

**Comment by madmonkey1907** [comment]
something like lsof -n | grep -F "/dev/fb0" might work. note that there are already uistop and uistart functions, we can add uilist, uipause and uiresume to aid this as well.

**Pull request closed without merging**
