### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by condiczek**

### CODE REVIEW

**Comment by ClusterM** [comment]
I'll create some translation tool soon, please wait.

**Comment by condiczek** [comment]
yep, i read that before, but its (i think) fully translated - all the files like your russian translation ;) btw brilliant work with folder manager !

**Comment by ClusterM** [comment]
Ok :)

**Comment by ClusterM** [comment]
Please write me on e-mail: clusterrr@clusterrr.com
I want to give you access to: https://docs.google.com/spreadsheets/d/1yrXH-6g61klKmuXTVf3f0ah8DCQObu-9YEJRoWTeuik/edit?usp=sharing

**Pull request merged**
