### PR TITLE
Translation Spanish of Spain

### PR DESCRIPTION
**Pull request by NaikiTurincondeliphone**
This is a translation from hakchi2 Spanish to Spanish

### CODE REVIEW

**Comment by ClusterM** [comment]
Seems like ths is not full translation. Do you really want to add this now?

**Comment by NaikiTurincondeliphone** [comment]
Yes, add that I have translated, since it is the most important thing. Then I'll look at what's missing and write it down in a notes file

Naiki

www.turincondeliphone.com<http://www.turincondeliphone.com>




On Fri, Jan 13, 2017 at 11:35 AM +0100, "ClusterM" <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems like ths is not full translation. Do you really want to add this now?

**Comment by NaikiTurincondeliphone** [comment]
Well, I have already found the other file to translate (MainForm.resx), in a few hours I modify it and upload it here :)

**Comment by ClusterM** [comment]
Re: [ClusterM/hakchi2] Create Resources.es-ES.resx (#4)


Hi.

You need to create file with suffix and insert only translated string.

I will try to create tool for easy translation soon. It's better to wait.





Well, I have already found the other file to translate (MainForm.resx), in a few hours I modify it and upload it here :)
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




-- 
С уважением,
 Алексей                          mailto:clusterrr@clusterrr.com

**Comment by PATWIST** [comment]
I'm looking forward to tool for translation :-) So even my young cousing can add games :-)

Greetings from Slovakia ;-)

**Comment by ClusterM** [comment]
I'll make translate tool, please wait for it.

**Comment by NaikiTurincondeliphone** [comment]
Thanks!

**Comment by Hedda** [comment]
@ClusterM instead of reinvesting the wheel for translations, highly recommend that the project would use Transifex language translation crowdsourcing services as suggested here:

https://github.com/ClusterM/hakchi2/issues/138

Again, suggest that you setup a new project for Hakchi (and NES/Famicom Mini) on Transifex translation services to get crowdsourced translations from your community.

https://en.wikipedia.org/wiki/Transifex

Many popular open source software projects use Transifex workflows to get free string language translations from their communities.

Example of an open source project using Transifex for many years is Kodi as you can read here:
https://kodi.tv/new-translation-service/
and here:
http://kodi.wiki/view/Translation_System

For end-users wanting to help out with the project using Transifex to translate strings is as easy as using a wiki.

Users just need to register an account for free on Transifex then join the project for the languages they know and begin to translate strings they understand.

All you need to do is point to files on GitHub you want translating and then copy/pull them from Transifex on a regular bases (usually before each release).

**Comment by ClusterM** [comment]
Transifex is not very good. It's better to use tools like ResxTranslator.

**Comment by ClusterM** [comment]
Please write me on e-mail: clusterrr@clusterrr.com
I want to give you access to: https://docs.google.com/spreadsheets/d/1yrXH-6g61klKmuXTVf3f0ah8DCQObu-9YEJRoWTeuik/edit?usp=sharing

**Comment by NaikiTurincondeliphone** [comment]
It's already sent e-mail :)

**Pull request closed without merging**
